name: test
channels:
  - conda-forge
  - defaults
dependencies:
  # obspy
  - numpy=1.20
  - scipy=1.7
  - matplotlib=3.3
  - decorator
  - lxml
  - requests
  - setuptools
  - sqlalchemy
  # soft dependencies
  - cartopy
  - geographiclib
  - pyshp
  # tests
  - packaging
  - pyproj
  - pytest
  - pytest-cov
  - pytest-json-report >= 1.4
